"""
Command-line entry point for the Scene Creator pipeline.

This file is used for running the Scene Agent manually during development.
It creates a demo RequestManagerContract, sends it into the pipeline, and prints
the files generated by the pipeline.
"""

import sys
from typing import Optional

from scene_agent.models.scene_request import RequestManagerContract
from scene_agent.pipeline import run_scene_creator_pipeline


# everything here is hardcoded, need to be changed in the future.
# what this class does is basically make something called contract,
# a contract looks a lot like a prompt, it has all the information the agent needs to know to generate the scene,
# the contract is then sent to the pipeline, which runs the agent and generates the files.
def build_demo_contract(argv: list[str]) -> RequestManagerContract:
    """
    Build a demo contract from command-line arguments.

    This is temporary until the real Request Manager sends an approved contract.
    """

    # First argument can override the local Godot project directory.
    project_directory_path = argv[0] if len(argv) >= 1 else "C:/test/GodotProject"

    # Remaining arguments can override the main game mechanic.
    game_mechanic = (
        " ".join(argv[1:])
        if len(argv) >= 2
        else "2D side-scroller moving right like Mario"
    )

    return RequestManagerContract(
        project_directory_path=project_directory_path,
        game_mechanic=game_mechanic,
        enemy_interaction=("Player takes damage on touch, enemies die if jumped on."),
        start_screen_instructions=(
            "Create a simple start screen with a title and a Start button."
        ),
        character_abilities=["run", "jump"],
    )


def main(argv: Optional[list[str]] = None) -> int:
    """
    Run the Scene Creator pipeline from the command line.
    """

    argv = argv if argv is not None else sys.argv[1:]

    try:
        # Build a temporary contract for local development and manual testing.
        contract = build_demo_contract(argv)

        print("Running Scene Creator pipeline...")
        print(f"Project directory: {contract.project_directory_path}")
        print(f"Game mechanic: {contract.game_mechanic}")

        # Run the real internal pipeline.
        result = run_scene_creator_pipeline(contract)

        print("\nPipeline finished successfully.")
        print(f"Status: {result.status}")

        print("\nGenerated files:")
        for generated_file in result.generated_files:
            print(f"- {generated_file.file_path} -> {generated_file.saved_path}")

        return 0

    except Exception as error:
        print(f"Scene Creator pipeline failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
